version: "3.9"

services:
  ppo:
    build: .
    container_name: ppo_agent
    environment:
      - AGENT=PPO
    volumes:
      - D:\drl_results:/app/results

  sac:
    build: .
    container_name: sac_agent
    environment:
      - AGENT=SAC
    volumes:
      - D:\drl_results:/app/results

  td3:
    build: .
    container_name: td3_agent
    environment:
      - AGENT=TD3
    volumes:
      - D:\drl_results:/app/results

  ddpg:
    build: .
    container_name: ddpg_agent
    environment:
      - AGENT=DDPG
    volumes:
      - D:\drl_results:/app/results

  a2c:
    build: .
    container_name: a2c_agent
    environment:
      - AGENT=A2C
    volumes:
      - D:\drl_results:/app/results

  dqn:
    build: .
    container_name: dqn_agent
    environment:
      - AGENT=DQN
    volumes:
      - D:\drl_results:/app/results

  maddpg:
    build: .
    container_name: maddpg_agent
    environment:
      - AGENT=MADDPG
    volumes:
      - D:\drl_results:/app/results
